-- Bu ifade ile belirtilen sayidaki ilk kayitlara ulasir. Select ifadesinden hemen sonra yazilsa da, once tum sorguyu calistirir ve en son top calisir...

-- Employees tablosundaki ilk 3 kayda ait tum sutunlari listeleyiniz...
select top 3 * from Employees

-- Employees tablosundaki unvanina gore azalarak siralanan ilk 5 kaydin adi, soyadi ve unvanini listeleyiniz...
select top 5 FirstName, LastName, TitleOfCourtesy from Employees order by TitleOfCourtesy desc

-- Employees tablosundaki kayitlari yaslarina gore buyukten kucuge siraladiktan sonra, olusacak sonuc kumesinin %25'lik kismini listeleyiniz...
select top 25 percent * from Employees
order by year(getdate()) - year(BirthDate) desc

-- Eger yuzde hesabindan cikan sonuc 3.2 gibi bir degerse, bu sonucu her zaman yukari yuvarlar ve 4 olarak verir...